### ISSUE TITLE
Error at startup: "attempt to index field 'ft_filter' (a nil value)"

### ISSUE THREAD

**Issue by wimstefan** [uga-rosa/ccc.nvim#37]
### Not a question

- [X] This is not a question. If you have a question, use [discussions](https://github.com/uga-rosa/ccc.nvim/discussions).

### Description

When starting up neovim I get this error message:
```lua
Error detected while processing BufEnter Autocommands for "*":
Error executing lua callback: .../site/pack/packer/start/ccc.nvim/lua/ccc/highlighter.lua:52: attempt to index field 'ft_filter' (a nil value)
stack traceback:
  .../site/pack/packer/start/ccc.nvim/lua/ccc/highlighter.lua:52: in function 'enable'
  .../site/pack/packer/start/ccc.nvim/lua/ccc/config/init.lua:58: in function <.../site/pack/packer/start/ccc.nvim/lua/ccc/config/init.lua:52>
```

### Environments

- **OS:**
  Gentoo Linux ~amd64

- **Neovim version:**
NVIM v0.9.0-dev-26-g06f4edc
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3 

### Minimal reproducible full config

```lua
     use({
      'uga-rosa/ccc.nvim',
      config = function()
        require('ccc').setup({
          highlighter = {
            auto_enable = true
          }
        })
        vim.keymap.set('n', ',ct', vim.cmd.CccHighlighterToggle)
        vim.keymap.set('n', ',cp', vim.cmd.CccPick)
      end
    })
```

### Steps to reproduce

Just start neovim with `nvim` and the error pops up.

My full config is [here](https://github.com/wimstefan/dotfiles/blob/master/config/nvim/init.lua) just in case ...

### Expected behavior

No error.

### Actual behavior

```lua
Error detected while processing BufEnter Autocommands for "*":
Error executing lua callback: .../site/pack/packer/start/ccc.nvim/lua/ccc/highlighter.lua:52: attempt to index field 'ft_filter' (a nil value)
stack traceback:
  .../site/pack/packer/start/ccc.nvim/lua/ccc/highlighter.lua:52: in function 'enable'
  .../site/pack/packer/start/ccc.nvim/lua/ccc/config/init.lua:58: in function <.../site/pack/packer/start/ccc.nvim/lua/ccc/config/init.lua:52>
```

**Comment by uga-rosa** [comment]
Fixed in #36.
Thank you @rcarriga.

**Comment by wimstefan** [comment]
@uga-rosa & @rcarriga: thanks to both of you! 🙏🏼👍🏼

**Comment by Avimitin** [comment]
Still getting same error if I am using lazy-loading:

```lua
use  {
    "uga-rosa/ccc.nvim",
    config = function()
      require("ccc").setup()
    end,
    cmd = {
      "CccPick",
      "CccHighlighterEnable",
    },
  },
```

* Error

```text
E5108: Error executing lua ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:171: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:83: Vim:Error executing Lua callback: ...im/site/pack/packer/opt/ccc.nvim/lua/ccc/highlighter.lua:52: a
ttempt to index field 'ft_filter' (a nil value)
stack traceback:
        [C]: in function 'cmd'
        ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:171: in function <...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:167>
        [string ":lua"]:1: in main chunk
```
